ICDC-1707
CBIIT/bento-icdc-frontend pull request #150
Opened 2021-04-16 18:07 UTC by tyudosen

Fixed error in the headers of .csv files downloaded from the Dashboard,

2021-04-16 18:46 UTC, rana22 commented on package.json
> +    "axios": "^0.21.1",
We can update version later at once. It would be easy to track if issue is related to dependencies.

2021-04-16 18:59 UTC, rana22 approved these changes

2021-04-16 19:05 UTC, rana22 approved these changes

2021-04-16 23:45 UTC, iksheth requested changes

2021-04-16 23:45 UTC, iksheth commented on package.json
> -    "axios": "^0.19.1",
@tyudosen Please revert this change.

2021-04-17 01:38 UTC, tyudosen commented on package.json
> -    "axios": "^0.19.1",
done

2021-04-19 21:47 UTC, iksheth approved these changes
LGTM 👍🏻

2021-04-19 21:47 UTC, merged