ICDC-2477
CBIIT/bento-icdc-frontend pull request #543
Opened 2022-04-07 17:18 UTC by tyudosen

### New Features
Apply the new design for increased visibility of ICDC's tool tip icons

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2022-04-07 19:09 UTC, rana22 approved these changes
LGTM

2022-04-11 15:31 UTC, iksheth requested changes

2022-04-11 15:31 UTC, iksheth commented on src/components/GridWithFooter/GridView.js
> +  // topButtonGroup: {
Can we remove this commented styling if not required in future?

2022-04-11 15:31 UTC, iksheth commented on src/components/GridWithFooter/GridView.js
> +    // verticalAlign: 'top',
same

2022-04-11 16:16 UTC, iksheth approved these changes

2022-04-11 16:16 UTC, merged