Gov shut down banner
CBIIT/bento-icdc-frontend pull request #901
Opened 2023-11-14 20:31 UTC by rana22

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2023-11-14 20:53 UTC, iksheth requested changes

2023-11-14 20:53 UTC, iksheth commented on public/index.html
> +    <!-- <div id="govAlertMsg">
@rana22 can we these comments?

2023-11-14 20:53 UTC, iksheth commented on src/components/Header/NavHeaderWithAlert.js
> +const urlLink = 'https://cbiit.github.io/nci-softwaresolutions-elements/banners/government-shutdown.html';
@rana22 this is url for analysis teams. Can we replace with one with **"https://cbiit.github.io/crdc-alert-elements/banners/government-shutdown.html"**

2023-11-14 20:53 UTC, iksheth commented on src/components/Layout/LayoutView.js
> +// import Header from '../Header/HeaderView';
unused code. Can we remove it?

2023-11-14 20:53 UTC, iksheth commented on public/index.html
> +    <script src="https://cbiit.github.io/nci-softwaresolutions-elements/components/include-html.js"></script>
@rana22 looks like url is wrong. Correct url: "https://cbiit.github.io/crdc-alert-elements/components/include-html.js"

2023-11-15 20:26 UTC, closed without merging

2023-11-15 20:26 UTC, rana22 commented
closing this PR